<a href="https://colab.research.google.com/github/Saranchana/DW/blob/master/Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

#1. Data Gathering

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/plenoi/CMU_DataScience/master/DIPEP.csv',header=None)
df

0             1             2    ...       398       399  400
0       0  9.999999e+06  9.999999e+06  ... -1.000000 -0.718446 -1.0
1       0 -1.000000e+00 -1.000000e+00  ... -0.312254 -1.000000 -1.0
2       0 -1.000000e+00 -8.400000e-01  ... -1.000000 -1.000000 -1.0
3       0 -1.000000e+00 -1.000000e+00  ... -0.811075 -0.716612 -1.0
4       0 -1.000000e+00 -1.000000e+00  ... -1.000000 -1.000000 -1.0
...   ...           ...           ...  ...       ...       ...  ...
3582    1 -1.000000e+00 -1.000000e+00  ... -1.000000 -1.000000 -1.0
3583    1 -7.181470e-01 -1.000000e+00  ... -1.000000 -0.306773 -1.0
3584    1 -1.000000e+00 -8.545460e-01  ... -1.000000 -0.589623 -1.0
3585    1 -1.000000e+00 -7.064220e-01  ... -1.000000 -1.000000 -1.0
3586    1 -8.165830e-01 -9.195980e-01  ... -1.000000 -1.000000 -1.0

[3587 rows x 401 columns]

#2. Data Pre-Processing

In [31]:
df.isnull().sum(axis=0)

0      0
1      0
2      0
3      0
4      1
      ..
396    0
397    0
398    0
399    0
400    0
Length: 401, dtype: int64

In [32]:
df_clean = df.dropna(axis=0)
df_clean

0             1             2    ...       398       399  400
0       0  9.999999e+06  9.999999e+06  ... -1.000000 -0.718446 -1.0
1       0 -1.000000e+00 -1.000000e+00  ... -0.312254 -1.000000 -1.0
2       0 -1.000000e+00 -8.400000e-01  ... -1.000000 -1.000000 -1.0
3       0 -1.000000e+00 -1.000000e+00  ... -0.811075 -0.716612 -1.0
4       0 -1.000000e+00 -1.000000e+00  ... -1.000000 -1.000000 -1.0
...   ...           ...           ...  ...       ...       ...  ...
3581    1 -1.000000e+00 -8.341970e-01  ... -0.593696 -1.000000 -1.0
3582    1 -1.000000e+00 -1.000000e+00  ... -1.000000 -1.000000 -1.0
3583    1 -7.181470e-01 -1.000000e+00  ... -1.000000 -0.306773 -1.0
3585    1 -1.000000e+00 -7.064220e-01  ... -1.000000 -1.000000 -1.0
3586    1 -8.165830e-01 -9.195980e-01  ... -1.000000 -1.000000 -1.0

[3585 rows x 401 columns]

In [33]:
df_clean.shape

(3585, 401)

แยก Label ออกจาก Data

In [0]:
df_clean = df.dropna()
y =df_clean.iloc[:,0]
X = df_clean.iloc[:,1:-1]

In [35]:

y.shape

(3585,)

In [36]:
X.shape

(3585, 399)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train ,y_val= train_test_split(X, y, test_size=0.20, random_state=0)

In [38]:
X_train.shape

(2868, 399)

In [39]:

X_val.shape

(717, 399)

MIN-MAX

In [0]:
from sklearn.preprocessing import MinMaxScaler
scl = MinMaxScaler()
scl.fit(X_train)
X_train_norm = scl.transform(X_train)
X_val_norm = scl.transform(X_val)

In [41]:
X_train_norm.max(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [42]:
X_train_norm.min(axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [43]:
X_val_norm.max(axis=0)

array([8.53799000e-08, 6.21360000e-08, 5.32127050e-01, 8.99468000e-01,
       7.54339000e-01, 5.24590400e-01, 1.10000110e+00, 6.96078500e-01,
       4.56249350e-01, 1.01818323e+00, 5.22059700e-01, 1.26421851e+00,
       3.19819500e-01, 6.06837500e-01, 4.76190000e-01, 6.10170500e-01,
       4.06060500e-01, 5.40440950e-01, 7.60273000e-01, 3.88890000e-01,
       8.67582500e-01, 1.06779654e+00, 6.91861000e-01, 4.15584000e-01,
       4.61539200e-01, 6.98113000e-01, 7.50002000e-01, 4.61021150e-01,
       7.60328000e-01, 2.83185500e-01, 4.18181000e-01, 8.25581500e-01,
       5.52326000e-01, 9.34884000e-01, 2.86291000e-01, 7.99999500e-01,
       5.88236000e-01, 9.34211500e-01, 5.88605500e-01, 6.36792500e-01,
       6.21621000e-01, 5.48914250e-01, 9.11502500e-01, 5.12456000e-01,
       9.02519000e-01, 1.05540475e+00, 8.03022000e-01, 4.02368500e-01,
       9.86683000e-01, 1.28767247e+00, 7.54388000e-01, 3.52941000e-01,
       6.24465000e-01, 3.68853000e-01, 8.98549500e-01, 6.43834000e-01,
      

In [44]:
X_val_norm.min(axis=0)

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.078704  ,
       -0.06144636,  0.1278935 ,  0.0045725 ,  0.325795  ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [45]:
y_train

2284    1
1929    1
422     0
2941    1
2465    1
       ..
835     0
3264    1
1653    1
2607    1
2732    1
Name: 0, Length: 2868, dtype: int64

In [46]:
y_val

1015    0
1341    1
2735    1
558     0
3559    1
       ..
2060    1
1952    1
3134    1
861     0
2717    1
Name: 0, Length: 717, dtype: int64

#Create Model : Support Vector Machine

In [51]:
from sklearn.svm import SVC
clf = SVC(C=2.0, degree=6, gamma='scale')
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(clf, X_train_norm, y_train, cv=25)
accuracy.mean()

0.805123543491412

In [48]:
#Test Model besed on Validation Accuracy
clf.fit(X_train_norm,y_train)
y_predict = clf.predict(X_val_norm)
sum(y_predict == y_val) / len(y_val)

0.7852161785216178